spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/comfortyDB
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect