version: '3.1'
services:
  postgres-db:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: comfortyDB
    container_name: postgres-db
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - mynetwork
  
  comforty:
    image: abdo001/comforty:v3
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/comfortyDB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
    container_name: comforty-backend
    depends_on:
      - postgres-db
    networks:
      - mynetwork
      

networks:
  mynetwork:
    driver: bridge
